rules:
    blacklist_http_types:
        - image/jpeg
        - image/png
        - image/gif
        - warc/revisit
        - text/css
        - application/javascript
        - image/vnd.microsoft.icon